- name: Setup basic services
  import_playbook: site.step-11-infrastructure.yml

- name: Setup persistence services
  import_playbook: site.step-20-persistent.yml

- name: Setup app services
  import_playbook: site.step-40-app-node.yml

- hosts: vagrant
  roles:
    - role: cs.packages
    - role: cs.sshd
    - role: cs.vagrant-sudo
    - role: geerlingguy.composer
      composer_version_branch: "{{ mageops_composer_version_branch | default("--2") }}"
      composer_keep_updated: true
    - role: cs.nodejs
    - role: cs.unison-server
    - role: cs.authorize-local-keys
      authorize_local_keys_for_users:
        - root
        - "{{ magento_user }}"
    - role: cs.mageops-cli-user
      mageops_cli_user: root
      mageops_cli_user_bashrc_fragments:
        - magento-root
        - elasticsearch
        - nginx
        - redis
        - varnish
  tasks:
    - include_tasks: "{{ mageops_project_vars_dir }}/{{ item }}"
      when: vagrant_tasks_project is defined
      loop: "{{ vagrant_tasks_project }}"

  vars:
    packages_install: "{{ mageops_packages_common + mageops_packages_vagrant_node }}"
    mageops_node_role: vagrant
    magento_redis_cache_l2: no
