- name: "Generate language detection config"
  template:
    src: language-redirect.conf.j2
    dest: "{{ nginx_language_redirect_multilevel_global_conf_path }}"
  notify: Reload nginx configs

- name: Register provisioned nginx config files
  set_fact:
    nginx_config_cleanup_provisioned_files: "{{ nginx_config_cleanup_provisioned_files + provisioned_configs }}"
  vars:
    provisioned_configs:
      - "{{ nginx_language_redirect_multilevel_global_conf_path }}"

- name: Generate server config for multilevel redirect
  template:
    src: language-redirect-rules.conf.j2
    dest: "{{ nginx_language_redirect_multilevel_server_default_conf_path }}"
  notify:
    - Reload nginx configs

- name: Register provisioned nginx config files
  set_fact:
    nginx_config_cleanup_provisioned_files: "{{ nginx_config_cleanup_provisioned_files + provisioned_configs }}"
  vars:
    provisioned_configs:
      - "{{ nginx_language_redirect_multilevel_server_default_conf_path }}"
