# Whether to stop the "builder" instance before creating AMI
aws_ami_build_stop_builder: true

aws_ami_build_ebs_volume_type: "{{ aws_ec2_ebs_volume_type | default('gp3', true) }}"
aws_ami_build_ebs_gp3_iops: "{{ aws_ec2_ebs_gp3_iops | default(3000, true) }}"
aws_ami_build_ebs_gp3_throughput: "{{ aws_ec2_ebs_gp3_throughput | default(125, true) }}"

# If set then extra info about built AMI will be saved as JSON
aws_ami_build_save_info_file_path: "{{ mageops_ansible_temp_dir }}/BUILD.AMI.json"
aws_ami_release_info: "{{ lookup('file', deploy_release_save_info_file_path, errors='warn', lstrip=true, rstrip=true) | default('{}', true) | from_json }}"