dependencies:
  - role: cs.nginx
  - role: cs.repo-mageops
    when: nginx_language_redirect_multilevel_geoip_mode == 'geolite2'
  - role: cs.geolite2
    when: nginx_language_redirect_multilevel_geoip_mode == 'geolite2'
